import React from "react";
import ExploreCourses from "@/components/Shared/ExploreCourses";

function page() {
  const allCourses = [
    {
      id: 1,
      title: "New Courses",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
    {
      id: 2,
      title: "New Courses",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
    {
      id: 3,
      title: "New Courses",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
    {
      id: 4,
      title: "New Courses",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
    {
      id: 5,
      title: "New Courses",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
    {
      id: 1,
      title: "Featured Courses",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
    {
      id: 2,
      title: "Featured Courses",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
    {
      id: 3,
      title: "Featured Courses",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
    {
      id: 4,
      title: "Featured Courses",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
    {
      id: 5,
      title: "Featured Courses",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
    {
      id: 1,
      title: "Course Bundles",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
    {
      id: 2,
      title: "Course Bundles",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
    {
      id: 3,
      title: "Course Bundles",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
    {
      id: 4,
      title: "Course Bundles",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
    {
      id: 5,
      title: "Course Bundles",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
    {
      id: 1,
      title: "Popular Courses",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
    {
      id: 2,
      title: "Popular Courses",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
    {
      id: 3,
      title: "Popular Courses",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
    {
      id: 4,
      title: "Popular Courses",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
    {
      id: 5,
      title: "Popular Courses",
      description: "3D Modelling and Animation with Blender",
      category: "3D Modeling",
      image: "/images/new-course-1.jpg",
      videoSrc: "/videos/video.mp4",
      studentTotal: "24",
      author: "Zainat Lincoln",
      oldPrice: "10,950",
      newPrice: "5,550",
    },
  ];
  return (
    <>
      <ExploreCourses courses={allCourses} title="New Courses" />
    </>
  );
}

export default page;
