"""
Django settings for XspaceCore project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
<<<<<<< HEAD
<<<<<<< HEAD

=======
=======
>>>>>>> master
from dotenv import load_dotenv
import os

#load .en variables
load_dotenv()

SECRET_KEY = os.getenv('YOUTUBE_API_KEY')
DEBUG = os.getenv('DEBUG') == 'True'
<<<<<<< HEAD
>>>>>>> aaaa89ef (Integrated Frontend)
=======
>>>>>>> master
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4n()j-^#4--68b$n80lt2843-5##4jh&)kr$_fl*w!u24j*ytq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
<<<<<<< HEAD
=======
    'Xspace',
    'rest_framework',
    'corsheaders'
>>>>>>> aaaa89ef (Integrated Frontend)
=======
    'Xspace',
    'rest_framework',
    'corsheaders'
>>>>>>> master
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> master

    'corsheaders.middleware.CorsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
<<<<<<< HEAD
>>>>>>> aaaa89ef (Integrated Frontend)
=======
>>>>>>> master
]

ROOT_URLCONF = 'XspaceCore.urls'

<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> master
#custom app user
AUTH_USER_MODEL = 'Xspace.User'


<<<<<<< HEAD
>>>>>>> aaaa89ef (Integrated Frontend)
=======
>>>>>>> master
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'XspaceCore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
<<<<<<< HEAD
<<<<<<< HEAD
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
=======
=======
>>>>>>> master
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'xspace',
        'USER':'mac',
        'PASSWORD':'password',
        'HOST':'localhost',
        'PORT':'5432',
<<<<<<< HEAD
>>>>>>> aaaa89ef (Integrated Frontend)
=======
>>>>>>> master
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
